/**
 * Demo content for legacy variant "ex-hover" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { justifiedLogoSocialDualSpaced } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = justifiedLogoSocialDualSpaced;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          label: 'Home',
          href: '#',
          current: true,
        },
        {
          label: 'Services',
          href: '#',
          submenu: {
            type: 'megamenu',
            rows: [
              {
                cols: [
                  {
                    blocks: [
                      {
                        type: 'list',
                        items: [
                          {
                            label: 'Website design',
                            href: '#',
                          },
                          {
                            label: 'ECommerce',
                            href: '#',
                          },
                          {
                            label: 'Website Maintenance',
                            href: '#',
                          },
                          {
                            label: 'Web Enhancements',
                            href: '#',
                          },
                        ],
                        heading: {
                          label: 'Web development',
                          href: '#',
                        },
                      },
                    ],
                  },
                  {
                    blocks: [
                      {
                        type: 'list',
                        items: [
                          {
                            label: 'Graphics',
                            href: '#',
                          },
                          {
                            label: 'Vectors',
                            href: '#',
                          },
                          {
                            label: 'Business cards',
                            href: '#',
                          },
                          {
                            label: 'Custom logo',
                            href: '#',
                          },
                        ],
                        heading: {
                          label: 'Design services',
                          href: '#',
                        },
                      },
                    ],
                  },
                  {
                    blocks: [
                      {
                        type: 'list',
                        items: [
                          {
                            label: 'Website design',
                            href: '#',
                          },
                          {
                            label: 'ECommerce',
                            href: '#',
                          },
                          {
                            label: 'Website Maintenance',
                            href: '#',
                          },
                          {
                            label: 'Web Enhancements',
                            href: '#',
                          },
                        ],
                        heading: {
                          label: 'Web development',
                          href: '#',
                        },
                      },
                    ],
                  },
                  {
                    blocks: [
                      {
                        type: 'list',
                        items: [
                          {
                            label: 'Facebook',
                            href: '#',
                          },
                          {
                            label: 'Search Engine Marketing',
                            href: '#',
                          },
                          {
                            label: 'Email Marketing',
                            href: '#',
                          },
                          {
                            label: 'Optimization (SEO)',
                            href: '#',
                          },
                        ],
                        heading: {
                          label: 'Web Marketing',
                          href: '#',
                        },
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
        {
          label: 'Team',
          href: '#',
        },
        {
          label: 'Portfolio',
          href: '#',
          submenu: {
            type: 'dropdown',
            items: [
              {
                label: 'Designs',
                href: '#',
              },
              {
                label: 'Graphics',
                href: '#',
              },
              {
                label: 'Programming',
                href: '#',
                submenu: {
                  type: 'dropdown',
                  items: [
                    {
                      label: 'Wordpress',
                      href: '#',
                    },
                    {
                      label: '.NET',
                      href: '#',
                    },
                    {
                      label: 'Javascript',
                      href: '#',
                    },
                    {
                      label: 'Python',
                      href: '#',
                    },
                    {
                      label: 'Java',
                      href: '#',
                    },
                  ],
                },
              },
              {
                label: 'Audio',
                href: '#',
              },
              {
                label: 'Video',
                href: '#',
              },
            ],
          },
        },
        {
          label: 'Contact',
          href: '#',
        },
      ],
    },
    {
      items: [
        {
          icon: 'facebook',
          href: '#',
        },
        {
          icon: 'twitter',
          href: '#',
        },
        {
          icon: 'instagram',
          href: '#',
        },
      ],
      social: true,
      spaced: true,
    },
  ],
  sections: [],
  logo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  panelLogo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  closeGlyph: '✕',
  assetBase: '/legacy/Examples/hover_files/',
};

export default content;
