/**
 * Demo content for legacy variant "ex-lists" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { justifiedLogoSocialDualSpaced } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = justifiedLogoSocialDualSpaced;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          label: 'Home',
          href: '#',
          current: true,
        },
        {
          label: 'Services',
          href: '#',
          submenu: {
            type: 'megamenu',
            rows: [
              {
                cols: [
                  {
                    blocks: [
                      {
                        type: 'list',
                        items: [
                          {
                            label: 'Website design',
                            href: '#',
                          },
                          {
                            label: 'ECommerce',
                            href: '#',
                          },
                          {
                            label: 'Website Maintenance',
                            href: '#',
                          },
                          {
                            label: 'Web Enhancements',
                            href: '#',
                          },
                        ],
                        heading: {
                          label: 'Web development',
                          href: '#',
                        },
                      },
                    ],
                  },
                  {
                    blocks: [
                      {
                        type: 'list',
                        items: [
                          {
                            label: 'Graphics',
                            href: '#',
                          },
                          {
                            label: 'Vectors',
                            href: '#',
                          },
                          {
                            label: 'Business cards',
                            href: '#',
                          },
                          {
                            label: 'Custom logo',
                            href: '#',
                          },
                        ],
                        heading: {
                          label: 'Design services',
                          href: '#',
                        },
                      },
                    ],
                  },
                  {
                    blocks: [
                      {
                        type: 'list',
                        items: [
                          {
                            label: 'Website design',
                            href: '#',
                          },
                          {
                            label: 'ECommerce',
                            href: '#',
                          },
                          {
                            label: 'Website Maintenance',
                            href: '#',
                          },
                          {
                            label: 'Web Enhancements',
                            href: '#',
                          },
                        ],
                        heading: {
                          label: 'Web development',
                          href: '#',
                        },
                      },
                    ],
                  },
                  {
                    blocks: [
                      {
                        type: 'list',
                        items: [
                          {
                            label: 'Facebook',
                            href: '#',
                          },
                          {
                            label: 'Search Engine Marketing',
                            href: '#',
                          },
                          {
                            label: 'Email Marketing',
                            href: '#',
                          },
                          {
                            label: 'Optimization (SEO)',
                            href: '#',
                          },
                        ],
                        heading: {
                          label: 'Web Marketing',
                          href: '#',
                        },
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
        {
          label: 'Team',
          href: '#',
        },
        {
          label: 'Marketplace items',
          href: '#',
          submenu: {
            type: 'megamenu',
            rows: [
              {
                cols: [
                  {
                    blocks: [
                      {
                        type: 'list',
                        items: [
                          {
                            label: 'Wordpress',
                            href: '#',
                          },
                          {
                            label: 'HTML',
                            href: '#',
                          },
                          {
                            label: 'Muse',
                            href: '#',
                          },
                          {
                            label: 'Magento',
                            href: '#',
                          },
                          {
                            label: 'Joomla',
                            href: '#',
                          },
                          {
                            label: 'Moodle',
                            href: '#',
                          },
                          {
                            label: 'Drupal',
                            href: '#',
                          },
                          {
                            label: 'Shopify',
                            href: '#',
                          },
                          {
                            label: 'Jigoshop',
                            href: '#',
                          },
                          {
                            label: 'Woocommerce',
                            href: '#',
                          },
                        ],
                        heading: {
                          label: 'Themes',
                          href: '#',
                        },
                      },
                    ],
                  },
                  {
                    blocks: [
                      {
                        type: 'list',
                        items: [
                          {
                            label: 'PHP Scripts',
                            href: '#',
                          },
                          {
                            label: 'Wordpress',
                            href: '#',
                          },
                          {
                            label: '.NET',
                            href: '#',
                          },
                          {
                            label: 'Javascript',
                            href: '#',
                          },
                          {
                            label: 'CSS',
                            href: '#',
                          },
                          {
                            label: 'Mobile',
                            href: '#',
                          },
                          {
                            label: 'Vue JS',
                            href: '#',
                          },
                          {
                            label: 'Angular',
                            href: '#',
                          },
                          {
                            label: 'Ember',
                            href: '#',
                          },
                          {
                            label: 'Meteor',
                            href: '#',
                          },
                        ],
                        heading: {
                          label: 'Code',
                          href: '#',
                        },
                      },
                    ],
                  },
                  {
                    blocks: [
                      {
                        type: 'list',
                        items: [
                          {
                            label: 'After Effects',
                            href: '#',
                          },
                          {
                            label: 'Premiere Pro',
                            href: '#',
                          },
                          {
                            label: 'Apple Motion',
                            href: '#',
                          },
                          {
                            label: 'Motion Graphics',
                            href: '#',
                          },
                          {
                            label: 'Stock Footage',
                            href: '#',
                          },
                          {
                            label: 'Cinema 4D',
                            href: '#',
                          },
                          {
                            label: 'Add-ons',
                            href: '#',
                          },
                          {
                            label: 'Logo',
                            href: '#',
                          },
                          {
                            label: 'News',
                            href: '#',
                          },
                          {
                            label: 'Wedding',
                            href: '#',
                          },
                        ],
                        heading: {
                          label: 'Video',
                          href: '#',
                        },
                      },
                    ],
                  },
                  {
                    blocks: [
                      {
                        type: 'list',
                        items: [
                          {
                            label: 'Print',
                            href: '#',
                          },
                          {
                            label: 'Web elements',
                            href: '#',
                          },
                          {
                            label: 'Add-ons',
                            href: '#',
                          },
                          {
                            label: 'Vectors',
                            href: '#',
                          },
                          {
                            label: 'Presentations',
                            href: '#',
                          },
                          {
                            label: 'Infographics',
                            href: '#',
                          },
                          {
                            label: 'Icons',
                            href: '#',
                          },
                          {
                            label: 'Fonts',
                            href: '#',
                          },
                          {
                            label: 'Logo',
                            href: '#',
                          },
                          {
                            label: 'Textures',
                            href: '#',
                          },
                        ],
                        heading: {
                          label: 'Graphics',
                          href: '#',
                        },
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
        {
          label: 'About us',
          href: '#',
        },
        {
          label: 'Contact',
          href: '#',
        },
      ],
    },
    {
      items: [
        {
          icon: 'facebook',
          href: '#',
        },
        {
          icon: 'twitter',
          href: '#',
        },
        {
          icon: 'instagram',
          href: '#',
        },
      ],
      social: true,
      spaced: true,
    },
  ],
  sections: [],
  logo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  panelLogo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  closeGlyph: '✕',
  assetBase: '/legacy/Examples/lists_files/',
};

export default content;
