/**
 * Demo content for legacy variant "ex-multidropdown" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { justifiedLogoSocialDualSpaced } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = justifiedLogoSocialDualSpaced;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          label: 'Home',
          href: '#',
          current: true,
        },
        {
          label: 'Services',
          href: '#',
          submenu: {
            type: 'dropdown',
            items: [
              {
                label: 'Design',
                href: '#',
              },
              {
                label: 'Audio',
                href: '#',
              },
              {
                label: 'Video',
                href: '#',
              },
              {
                label: 'Programming',
                href: '#',
                submenu: {
                  type: 'dropdown',
                  items: [
                    {
                      label: 'Wordpress',
                      href: '#',
                    },
                    {
                      label: '.NET',
                      href: '#',
                    },
                    {
                      label: 'Javascript',
                      href: '#',
                      submenu: {
                        type: 'dropdown',
                        items: [
                          {
                            label: 'Vue',
                            href: '#',
                          },
                          {
                            label: 'React',
                            href: '#',
                          },
                          {
                            label: 'Ember',
                            href: '#',
                          },
                          {
                            label: 'Angular',
                            href: '#',
                            submenu: {
                              type: 'dropdown',
                              items: [
                                {
                                  label: 'Angular',
                                  href: '#',
                                },
                                {
                                  label: 'Angular 2',
                                  href: '#',
                                },
                              ],
                              side: 'start',
                            },
                          },
                        ],
                        side: 'start',
                      },
                    },
                    {
                      label: 'Python',
                      href: '#',
                    },
                  ],
                },
              },
            ],
          },
        },
        {
          label: 'Team',
          href: '#',
        },
        {
          label: 'Portfolio',
          href: '#',
          submenu: {
            type: 'dropdown',
            items: [
              {
                label: 'Designs',
                href: '#',
              },
              {
                label: 'Graphics',
                href: '#',
              },
              {
                label: 'Programming',
                href: '#',
                submenu: {
                  type: 'dropdown',
                  items: [
                    {
                      label: 'Wordpress',
                      href: '#',
                    },
                    {
                      label: '.NET',
                      href: '#',
                    },
                    {
                      label: 'Javascript',
                      href: '#',
                      submenu: {
                        type: 'dropdown',
                        items: [
                          {
                            label: 'Vue',
                            href: '#',
                          },
                          {
                            label: 'React',
                            href: '#',
                          },
                          {
                            label: 'Ember',
                            href: '#',
                          },
                          {
                            label: 'Angular',
                            href: '#',
                            submenu: {
                              type: 'dropdown',
                              items: [
                                {
                                  label: 'Angular',
                                  href: '#',
                                },
                                {
                                  label: 'Angular 2',
                                  href: '#',
                                },
                              ],
                              side: 'start',
                            },
                          },
                        ],
                      },
                    },
                    {
                      label: 'Python',
                      href: '#',
                    },
                  ],
                },
              },
              {
                label: 'Audio',
                href: '#',
              },
              {
                label: 'Video',
                href: '#',
              },
              {
                label: 'ECommerce',
                href: '#',
              },
              {
                label: 'Vectors',
                href: '#',
              },
              {
                label: 'Logos',
                href: '#',
              },
              {
                label: 'Flyers',
                href: '#',
              },
              {
                label: 'Illustrations',
                href: '#',
              },
            ],
          },
        },
        {
          label: 'Contact',
          href: '#',
        },
      ],
    },
    {
      items: [
        {
          icon: 'facebook',
          href: '#',
        },
        {
          icon: 'twitter',
          href: '#',
        },
        {
          icon: 'instagram',
          href: '#',
        },
      ],
      social: true,
      spaced: true,
    },
  ],
  sections: [],
  logo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  panelLogo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  closeGlyph: '✕',
  assetBase: '/legacy/Examples/multidropdown_files/',
};

export default content;
