/**
 * Demo content for legacy variant "ex-megamenu" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { justifiedLogoSocialDualSpaced } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = justifiedLogoSocialDualSpaced;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          label: 'Home',
          href: '#',
          current: true,
        },
        {
          label: 'News',
          href: '#',
          submenu: {
            type: 'megamenu',
            rows: [
              {
                cols: [
                  {
                    blocks: [
                      {
                        type: 'image',
                        image: {
                          src: 'blue.jpeg',
                          alt: 'Responsive image',
                          className: 'img-fluid',
                        },
                      },
                      {
                        type: 'heading',
                        text: 'Lorem ipsum sit amet',
                        level: 6,
                        className: 'mt-3',
                      },
                      {
                        type: 'text',
                        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque nulla non neque tempor, ac ultrices massa condimentum. Nunc semper dictum lectus ultricies hendrerit. In ut lorem in urna convallis porttitor ut cursus nisi. Proin gravida, ligula a consectetur dapibus, urna tellus tincidunt justo',
                        className: 'm-0 text-justify',
                      },
                    ],
                    className: 'p-2',
                  },
                  {
                    blocks: [
                      {
                        type: 'image',
                        image: {
                          src: 'red.jpeg',
                          alt: 'Responsive image',
                          className: 'img-fluid',
                        },
                      },
                      {
                        type: 'heading',
                        text: 'Nunc semper dictum',
                        level: 6,
                        className: 'mt-3',
                      },
                      {
                        type: 'text',
                        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque nulla non neque tempor, ac ultrices massa condimentum. Nunc semper dictum lectus ultricies hendrerit. In ut lorem in urna convallis porttitor ut cursus nisi. Proin gravida, ligula a consectetur dapibus, urna tellus tincidunt justo',
                        className: 'm-0 text-justify',
                      },
                    ],
                    className: 'p-2',
                  },
                  {
                    blocks: [
                      {
                        type: 'image',
                        image: {
                          src: 'green.jpeg',
                          alt: 'Responsive image',
                          className: 'img-fluid',
                        },
                      },
                      {
                        type: 'heading',
                        text: 'Aliquam pellentesque',
                        level: 6,
                        className: 'mt-3',
                      },
                      {
                        type: 'text',
                        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque nulla non neque tempor, ac ultrices massa condimentum. Nunc semper dictum lectus ultricies hendrerit. In ut lorem in urna convallis porttitor ut cursus nisi. Proin gravida, ligula a consectetur dapibus, urna tellus tincidunt justo',
                        className: 'm-0 text-justify',
                      },
                    ],
                    className: 'p-2',
                  },
                ],
              },
            ],
          },
        },
        {
          label: 'Team',
          href: '#',
        },
        {
          label: 'Articles',
          href: '#',
          submenu: {
            type: 'megamenu',
            rows: [
              {
                cols: [
                  {
                    blocks: [
                      {
                        type: 'row',
                        row: {
                          cols: [
                            {
                              blocks: [
                                {
                                  type: 'image',
                                  image: {
                                    src: 'blue.jpeg',
                                    alt: 'Responsive image',
                                    className: 'img-fluid',
                                  },
                                },
                              ],
                              span: 3,
                            },
                            {
                              blocks: [
                                {
                                  type: 'text',
                                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque nulla non neque tempor, ac ultrices massa condimentum. Nunc semper dictum lectus ultricies hendrerit. In ut lorem in urna.',
                                  className: 'm-0 px-lg-3 text-justify',
                                },
                              ],
                              span: 9,
                            },
                          ],
                          className: 'mb-3',
                        },
                      },
                      {
                        type: 'row',
                        row: {
                          cols: [
                            {
                              blocks: [
                                {
                                  type: 'image',
                                  image: {
                                    src: 'red.jpeg',
                                    alt: 'Responsive image',
                                    className: 'img-fluid',
                                  },
                                },
                              ],
                              span: 3,
                            },
                            {
                              blocks: [
                                {
                                  type: 'text',
                                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque nulla non neque tempor, ac ultrices massa condimentum. Nunc semper dictum lectus ultricies hendrerit. In ut lorem in urna.',
                                  className: 'm-0 px-lg-3 text-justify',
                                },
                              ],
                              span: 9,
                            },
                          ],
                          className: 'mb-3',
                        },
                      },
                      {
                        type: 'row',
                        row: {
                          cols: [
                            {
                              blocks: [
                                {
                                  type: 'image',
                                  image: {
                                    src: 'green.jpeg',
                                    alt: 'Responsive image',
                                    className: 'img-fluid',
                                  },
                                },
                              ],
                              span: 3,
                            },
                            {
                              blocks: [
                                {
                                  type: 'text',
                                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque nulla non neque tempor, ac ultrices massa condimentum. Nunc semper dictum lectus ultricies hendrerit. In ut lorem in urna.',
                                  className: 'm-0 px-lg-3 text-justify',
                                },
                              ],
                              span: 9,
                            },
                          ],
                        },
                      },
                    ],
                    className: 'p-2',
                  },
                  {
                    blocks: [
                      {
                        type: 'row',
                        row: {
                          cols: [
                            {
                              blocks: [
                                {
                                  type: 'image',
                                  image: {
                                    src: 'red.jpeg',
                                    alt: 'Responsive image',
                                    className: 'img-fluid px-lg-2',
                                  },
                                },
                              ],
                              span: 6,
                            },
                            {
                              blocks: [
                                {
                                  type: 'image',
                                  image: {
                                    src: 'blue.jpeg',
                                    alt: 'Responsive image',
                                    className: 'img-fluid pl-lg-3',
                                  },
                                },
                              ],
                              span: 6,
                            },
                          ],
                          className: 'mb-3',
                        },
                      },
                      {
                        type: 'row',
                        row: {
                          cols: [
                            {
                              blocks: [
                                {
                                  type: 'text',
                                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque nulla non neque tempor, ac ultrices massa condimentum. Nunc semper dictum lectus ultricies hendrerit. In ut lorem in urna convallis porttitor ut cursus nisi. Proin gravida, ligula a consectetur dapibus, urna tellus tincidunt justo ac ultrices massa condimentum. Nunc semper dictum lectus ultricies hendrerit. In ut lorem in urna convallis porttitor ut cursus nisi.',
                                  className: 'm-0 pl-lg-2 text-justify',
                                },
                              ],
                            },
                          ],
                        },
                      },
                    ],
                    className: 'p-2',
                  },
                ],
              },
            ],
          },
        },
        {
          label: 'Contact',
          href: '#',
        },
      ],
    },
    {
      items: [
        {
          icon: 'facebook',
          href: '#',
        },
        {
          icon: 'twitter',
          href: '#',
        },
        {
          icon: 'instagram',
          href: '#',
        },
      ],
      social: true,
      spaced: true,
    },
  ],
  sections: [],
  logo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  panelLogo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  closeGlyph: '✕',
  assetBase: '/legacy/Examples/megamenu_files/',
};

export default content;
