/**
 * Demo content for legacy variant "ex-scrollspy" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { justifiedStickyLogoSocialDualSpaced } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = justifiedStickyLogoSocialDualSpaced;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          label: 'Home',
          href: '#home',
        },
        {
          label: 'Services',
          href: '#services',
        },
        {
          label: 'Team',
          href: '#team',
        },
        {
          label: 'Portfolio',
          href: '#portfolio',
        },
        {
          label: 'Contact',
          href: '#contact',
        },
      ],
    },
    {
      items: [
        {
          icon: 'facebook',
          href: '#',
        },
        {
          icon: 'twitter',
          href: '#',
        },
        {
          icon: 'instagram',
          href: '#',
        },
      ],
      social: true,
      spaced: true,
    },
  ],
  sections: [],
  logo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  panelLogo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  closeGlyph: '✕',
  assetBase: '/legacy/Examples/scrollspy_files/',
};

export default content;
