/**
 * Demo content for legacy variant "navigation43" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { justifiedLogoTriple } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = justifiedLogoTriple;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          icon: 'menu',
          label: 'Menu',
          wrapLabel: true,
          href: '#',
          variant: 'icon',
          hideItemInPanel: true,
        },
        {
          label: 'Catalog',
          href: '#',
        },
      ],
    },
    {
      items: [
        {
          label: 'NAVBAR',
          hiddenInPanel: true,
          href: '#',
          variant: 'brand',
        },
      ],
    },
    {
      items: [
        {
          icon: 'cart',
          label: 'Cart',
          wrapLabel: true,
          href: '#',
          variant: 'icon',
        },
        {
          icon: 'search',
          label: 'Search',
          wrapLabel: true,
          badge: '5',
          href: '#',
          variant: 'icon',
        },
      ],
    },
  ],
  sections: [],
  logo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  panelLogo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  closeGlyph: '✕',
  assetBase: '/legacy/Catalogue/catalogue_files/',
};

export default content;
