/**
 * Demo content for legacy variant "navigation10" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { plainLogoSectionEndSearchButton } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = plainLogoSectionEndSearchButton;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          label: 'Home',
          href: '#',
          current: true,
        },
        {
          label: 'Services',
          href: '#',
        },
        {
          label: 'Blog',
          href: '#',
        },
        {
          label: 'Contact',
          href: '#',
        },
      ],
    },
  ],
  sections: [
    {
      type: 'form',
      input: {
        type: 'search',
        name: 'search',
        placeholder: 'Search',
      },
      submit: {
        glyph: 'search',
      },
      push: 'end',
    },
    {
      type: 'button',
      label: 'Button',
      href: '#',
    },
  ],
  logo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  panelLogo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  closeGlyph: '✕',
  assetBase: '/legacy/Catalogue/catalogue_files/',
};

export default content;
