/**
 * Demo content for legacy variant "navigation20" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { plainLogoSearch } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = plainLogoSearch;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          icon: 'home',
          label: 'Home',
          wrapLabel: true,
          href: '#',
          variant: 'icon',
        },
        {
          icon: 'settings',
          label: 'Settings',
          wrapLabel: true,
          href: '#',
          variant: 'icon',
        },
        {
          icon: 'mail',
          label: 'Messages',
          wrapLabel: true,
          href: '#',
          variant: 'icon',
        },
      ],
    },
  ],
  sections: [
    {
      type: 'form',
      input: {
        type: 'search',
        name: 'search',
        placeholder: 'Search',
      },
      submit: {
        glyph: 'search',
      },
      place: 'before-menus',
    },
  ],
  logo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  panelLogo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  closeGlyph: '✕',
  assetBase: '/legacy/Catalogue/catalogue_files/',
};

export default content;
