/**
 * Demo content for legacy variant "navigation33" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { plainBrandDualMenuEnd } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = plainBrandDualMenuEnd;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          icon: 'search',
          label: 'Search',
          wrapLabel: true,
          labelHiddenInBar: true,
          href: '#',
        },
        {
          label: 'Home',
          href: '#',
          current: true,
        },
        {
          label: 'Services',
          href: '#',
        },
        {
          label: 'Blog',
          href: '#',
        },
        {
          label: 'Contact',
          href: '#',
        },
      ],
    },
    {
      items: [
        {
          icon: 'user',
          label: 'Sign in',
          wrapLabel: true,
          labelHiddenInBar: true,
          href: '#',
        },
        {
          icon: 'cart',
          label: 'Cart',
          wrapLabel: true,
          labelHiddenInBar: true,
          href: '#',
        },
      ],
      push: 'end',
    },
  ],
  sections: [],
  brand: {
    label: 'NAVIGATION',
    href: '#',
  },
  panelBrand: {
    label: 'NAVIGATION',
    href: '#',
  },
  closeGlyph: '✕',
};

export default content;
