/**
 * Demo content for legacy variant "navigation23" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { justifiedLogoDual } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = justifiedLogoDual;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          icon: 'home',
          label: 'Home',
          wrapLabel: true,
          href: '#',
          current: true,
        },
        {
          icon: 'settings',
          label: 'Services',
          wrapLabel: true,
          href: '#',
        },
        {
          icon: 'settings',
          label: 'Blog',
          wrapLabel: true,
          href: '#',
        },
        {
          icon: 'mail',
          label: 'Messages',
          wrapLabel: true,
          href: '#',
        },
      ],
    },
    {
      items: [
        {
          icon: 'search',
          label: 'Search',
          wrapLabel: true,
          href: '#',
          variant: 'icon',
        },
      ],
    },
  ],
  sections: [],
  logo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  panelLogo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  closeGlyph: '✕',
  assetBase: '/legacy/Catalogue/catalogue_files/',
};

export default content;
