/**
 * Demo content for legacy variant "navigation27" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { justifiedBrandSearchText } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = justifiedBrandSearchText;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          icon: 'sign-in',
          label: 'Sign in',
          wrapLabel: true,
          href: '#',
        },
        {
          icon: 'cart',
          label: 'Cart',
          wrapLabel: true,
          href: '#',
        },
      ],
    },
  ],
  sections: [
    {
      type: 'text',
      text: 'Tel.: 123 456 7890',
      place: 'before-menus',
    },
    {
      type: 'form',
      input: {
        type: 'search',
        name: 'search',
        placeholder: 'Search',
      },
      submit: {
        glyph: 'search',
      },
      place: 'before-menus',
    },
  ],
  brand: {
    label: 'NAVIGATION',
    href: '#',
  },
  panelBrand: {
    label: 'NAVIGATION',
    href: '#',
  },
  closeGlyph: '✕',
};

export default content;
