/**
 * Demo content for legacy variant "navigation6" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { plainBrandSectionEndSearch } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = plainBrandSectionEndSearch;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          label: 'Home',
          href: '#',
          current: true,
        },
        {
          label: 'Services',
          href: '#',
        },
        {
          label: 'Blog',
          href: '#',
        },
        {
          label: 'Contact',
          href: '#',
        },
      ],
    },
  ],
  sections: [
    {
      type: 'form',
      input: {
        type: 'search',
        name: 'search',
        placeholder: 'Search',
      },
      submit: {
        glyph: 'search',
      },
      push: 'end',
    },
  ],
  brand: {
    label: 'NAVIGATION',
    href: '#',
  },
  panelBrand: {
    label: 'NAVIGATION',
    href: '#',
  },
  closeGlyph: '✕',
};

export default content;
