/**
 * Demo content for legacy variant "navigation44" — the catalogue's own words.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import { justifiedLogo } from '../catalogue.js';
import type { NavxContent, NavxPreset } from '../types.js';

/** The chrome this content was written for. */
export const preset: NavxPreset = justifiedLogo;

export const content: NavxContent = {
  menus: [
    {
      items: [
        {
          image: {
            src: 'avatar.png',
            alt: 'logo',
          },
          label: 'My account',
          wrapLabel: true,
          href: '#',
          variant: 'avatar',
        },
        {
          label: 'Campaigns',
          href: '#',
          current: true,
        },
        {
          label: 'Reports',
          href: '#',
        },
        {
          label: 'Messages',
          href: '#',
        },
        {
          image: {
            src: 'avatar.png',
            alt: 'logo',
          },
          label: 'My account',
          wrapLabel: true,
          href: '#',
          variant: 'avatar',
          hideItemInPanel: true,
        },
      ],
    },
  ],
  sections: [],
  logo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  panelLogo: {
    image: {
      src: 'logo.png',
      alt: 'logo',
    },
    href: '#',
  },
  closeGlyph: '✕',
  assetBase: '/legacy/Catalogue/catalogue_files/',
};

export default content;
