/**
 * The catalogue presets — chrome only: layout, skin and which slots exist.
 *
 * GENERATED by tools/baseline/tools/extract-presets.mjs from the legacy
 * catalogue. Committed rather than built, because regenerating it needs the
 * separately-licensed legacy tree that this repo deliberately does not carry.
 * Edit the extractor, not this file.
 */

import type { NavxPreset } from './types.js';

/** Justified, a logo, social icons, 2 menus, a spaced menu, click to open. Reproduces 1 catalogue variant(s): ex-click. */
export const justifiedLogoSocialDualSpacedClick: NavxPreset = {
  id: 'justified-logo-social-dual-spaced-click',
  name: 'Justified, a logo, social icons, 2 menus, a spaced menu, click to open',
  slots: {
    menus: [
      {},
      {
        social: true,
        spaced: true,
      },
    ],
    sections: [],
    logo: true,
    panelLogo: true,
  },
  align: 'between',
  trigger: 'click',
};

/** Justified, a logo, social icons, 2 menus, a spaced menu. Reproduces 9 catalogue variant(s): ex-horizontal, ex-hover, ex-lists, ex-megamenu, ex-multidropdown, ex-overlay, ex-skins, navigation12, navigation26. */
export const justifiedLogoSocialDualSpaced: NavxPreset = {
  id: 'justified-logo-social-dual-spaced',
  name: 'Justified, a logo, social icons, 2 menus, a spaced menu',
  slots: {
    menus: [
      {},
      {
        social: true,
        spaced: true,
      },
    ],
    sections: [],
    logo: true,
    panelLogo: true,
  },
  align: 'between',
};

/** Justified, sticky, a logo, social icons, 2 menus, a spaced menu. Reproduces 2 catalogue variant(s): ex-scrollspy, ex-sticky. */
export const justifiedStickyLogoSocialDualSpaced: NavxPreset = {
  id: 'justified-sticky-logo-social-dual-spaced',
  name: 'Justified, sticky, a logo, social icons, 2 menus, a spaced menu',
  slots: {
    menus: [
      {},
      {
        social: true,
        spaced: true,
      },
    ],
    sections: [],
    logo: true,
    panelLogo: true,
  },
  align: 'between',
  position: 'sticky',
};

/** Centered, brand text. Reproduces 1 catalogue variant(s): navigation1. */
export const centeredBrand: NavxPreset = {
  id: 'centered-brand',
  name: 'Centered, brand text',
  slots: {
    menus: [{}],
    sections: [],
    brand: true,
  },
  align: 'center',
};

/** Plain, a logo. Reproduces 2 catalogue variant(s): navigation2, navigation21. */
export const plainLogo: NavxPreset = {
  id: 'plain-logo',
  name: 'Plain, a logo',
  slots: {
    menus: [{}],
    sections: [],
    logo: true,
    panelLogo: true,
  },
};

/** Justified, a logo. Reproduces 6 catalogue variant(s): navigation3, navigation19, navigation22, navigation44, navigation45, navigation46. */
export const justifiedLogo: NavxPreset = {
  id: 'justified-logo',
  name: 'Justified, a logo',
  slots: {
    menus: [{}],
    sections: [],
    logo: true,
    panelLogo: true,
  },
  align: 'between',
};

/** Plain, a logo, a section at the trailing edge, a button. Reproduces 1 catalogue variant(s): navigation4. */
export const plainLogoSectionEndButton: NavxPreset = {
  id: 'plain-logo-section-end-button',
  name: 'Plain, a logo, a section at the trailing edge, a button',
  slots: {
    menus: [{}],
    sections: ['button'],
    logo: true,
    panelLogo: true,
    sectionPush: true,
  },
};

/** Plain, a logo, a button. Reproduces 1 catalogue variant(s): navigation5. */
export const plainLogoButton: NavxPreset = {
  id: 'plain-logo-button',
  name: 'Plain, a logo, a button',
  slots: {
    menus: [{}],
    sections: ['button'],
    logo: true,
    panelHeader: {
      push: 'start',
    },
    panelLogo: true,
  },
};

/** Plain, brand text, a section at the trailing edge, a search field. Reproduces 1 catalogue variant(s): navigation6. */
export const plainBrandSectionEndSearch: NavxPreset = {
  id: 'plain-brand-section-end-search',
  name: 'Plain, brand text, a section at the trailing edge, a search field',
  slots: {
    menus: [{}],
    sections: ['form'],
    brand: true,
    panelBrand: true,
    sectionPush: true,
  },
};

/** Plain, brand text, a search field. Reproduces 1 catalogue variant(s): navigation7. */
export const plainBrandSearch: NavxPreset = {
  id: 'plain-brand-search',
  name: 'Plain, brand text, a search field',
  slots: {
    menus: [{}],
    sections: ['form'],
    brand: true,
    panelHeader: {
      push: 'start',
    },
    panelBrand: true,
  },
};

/** Justified, a logo, a button. Reproduces 2 catalogue variant(s): navigation8, navigation24. */
export const justifiedLogoButton: NavxPreset = {
  id: 'justified-logo-button',
  name: 'Justified, a logo, a button',
  slots: {
    menus: [{}],
    sections: ['button'],
    logo: true,
    panelLogo: true,
  },
  align: 'between',
};

/** Justified, brand text, a search field. Reproduces 1 catalogue variant(s): navigation9. */
export const justifiedBrandSearch: NavxPreset = {
  id: 'justified-brand-search',
  name: 'Justified, brand text, a search field',
  slots: {
    menus: [{}],
    sections: ['form'],
    brand: true,
    panelBrand: true,
  },
  align: 'between',
};

/** Plain, a logo, a section at the trailing edge, a search field, a button. Reproduces 1 catalogue variant(s): navigation10. */
export const plainLogoSectionEndSearchButton: NavxPreset = {
  id: 'plain-logo-section-end-search-button',
  name: 'Plain, a logo, a section at the trailing edge, a search field, a button',
  slots: {
    menus: [{}],
    sections: ['form', 'button'],
    logo: true,
    panelLogo: true,
    sectionPush: true,
  },
};

/** Plain, a logo, social icons, 2 menus, a menu at the trailing edge, a spaced menu. Reproduces 1 catalogue variant(s): navigation11. */
export const plainLogoSocialDualMenuEndSpaced: NavxPreset = {
  id: 'plain-logo-social-dual-menu-end-spaced',
  name: 'Plain, a logo, social icons, 2 menus, a menu at the trailing edge, a spaced menu',
  slots: {
    menus: [
      {},
      {
        social: true,
        push: 'end',
        spaced: true,
      },
    ],
    sections: [],
    logo: true,
    panelLogo: true,
  },
};

/** Plain, a logo, 2 menus, a menu at the trailing edge. Reproduces 3 catalogue variant(s): navigation13, navigation16, navigation30. */
export const plainLogoDualMenuEnd: NavxPreset = {
  id: 'plain-logo-dual-menu-end',
  name: 'Plain, a logo, 2 menus, a menu at the trailing edge',
  slots: {
    menus: [
      {},
      {
        push: 'end',
      },
    ],
    sections: [],
    logo: true,
    panelLogo: true,
  },
};

/** Plain, a logo, 2 menus. Reproduces 2 catalogue variant(s): navigation14, navigation17. */
export const plainLogoDual: NavxPreset = {
  id: 'plain-logo-dual',
  name: 'Plain, a logo, 2 menus',
  slots: {
    menus: [{}, {}],
    sections: [],
    logo: true,
    panelHeader: {
      push: 'start',
    },
    panelLogo: true,
  },
};

/** Justified, a logo, 2 menus. Reproduces 4 catalogue variant(s): navigation15, navigation18, navigation23, navigation31. */
export const justifiedLogoDual: NavxPreset = {
  id: 'justified-logo-dual',
  name: 'Justified, a logo, 2 menus',
  slots: {
    menus: [{}, {}],
    sections: [],
    logo: true,
    panelLogo: true,
  },
  align: 'between',
};

/** Plain, a logo, a search field. Reproduces 1 catalogue variant(s): navigation20. */
export const plainLogoSearch: NavxPreset = {
  id: 'plain-logo-search',
  name: 'Plain, a logo, a search field',
  slots: {
    menus: [{}],
    sections: ['form'],
    logo: true,
    panelHeader: {
      push: 'start',
    },
    panelLogo: true,
  },
};

/** Justified, a logo, a search field. Reproduces 1 catalogue variant(s): navigation25. */
export const justifiedLogoSearch: NavxPreset = {
  id: 'justified-logo-search',
  name: 'Justified, a logo, a search field',
  slots: {
    menus: [{}],
    sections: ['form'],
    logo: true,
    panelLogo: true,
  },
  align: 'between',
};

/** Justified, brand text, a search field, a text block. Reproduces 1 catalogue variant(s): navigation27. */
export const justifiedBrandSearchText: NavxPreset = {
  id: 'justified-brand-search-text',
  name: 'Justified, brand text, a search field, a text block',
  slots: {
    menus: [{}],
    sections: ['text', 'form'],
    brand: true,
    panelHeader: {
      push: 'start',
    },
    panelBrand: true,
  },
  align: 'between',
};

/** Plain, brand text, 2 menus, a menu at the leading edge. Reproduces 1 catalogue variant(s): navigation28. */
export const plainBrandDualMenuStart: NavxPreset = {
  id: 'plain-brand-dual-menu-start',
  name: 'Plain, brand text, 2 menus, a menu at the leading edge',
  slots: {
    menus: [
      {
        push: 'start',
      },
      {},
    ],
    sections: [],
    brand: true,
    panelBrand: true,
  },
};

/** Justified, brand text, 2 menus. Reproduces 1 catalogue variant(s): navigation29. */
export const justifiedBrandDual: NavxPreset = {
  id: 'justified-brand-dual',
  name: 'Justified, brand text, 2 menus',
  slots: {
    menus: [{}, {}],
    sections: [],
    brand: true,
    panelBrand: true,
  },
  align: 'between',
};

/** Plain, a logo, 2 menus, the first menu at the trailing edge. Reproduces 1 catalogue variant(s): navigation32. */
export const plainLogoDualLeadMenuEnd: NavxPreset = {
  id: 'plain-logo-dual-lead-menu-end',
  name: 'Plain, a logo, 2 menus, the first menu at the trailing edge',
  slots: {
    menus: [
      {
        push: 'end',
      },
      {},
    ],
    sections: [],
    logo: true,
    panelLogo: true,
  },
};

/** Plain, brand text, 2 menus, a menu at the trailing edge. Reproduces 1 catalogue variant(s): navigation33. */
export const plainBrandDualMenuEnd: NavxPreset = {
  id: 'plain-brand-dual-menu-end',
  name: 'Plain, brand text, 2 menus, a menu at the trailing edge',
  slots: {
    menus: [
      {},
      {
        push: 'end',
      },
    ],
    sections: [],
    brand: true,
    panelBrand: true,
  },
};

/** Plain, logo above the bar, brand text. Reproduces 1 catalogue variant(s): navigation34. */
export const plainLogoTopBrand: NavxPreset = {
  id: 'plain-logo-top-brand',
  name: 'Plain, logo above the bar, brand text',
  slots: {
    menus: [{}],
    sections: [],
    brand: true,
    panelBrand: true,
  },
  logo: 'top',
};

/** Plain, logo above the bar. Reproduces 2 catalogue variant(s): navigation35, navigation36. */
export const plainLogoTop: NavxPreset = {
  id: 'plain-logo-top',
  name: 'Plain, logo above the bar',
  slots: {
    menus: [{}],
    sections: [],
    logo: true,
    panelLogo: true,
  },
  logo: 'top',
};

/** Centered, a logo. Reproduces 1 catalogue variant(s): navigation37. */
export const centeredLogo: NavxPreset = {
  id: 'centered-logo',
  name: 'Centered, a logo',
  slots: {
    menus: [{}],
    sections: [],
    logo: true,
    panelLogo: true,
  },
  align: 'center',
};

/** Justified, a logo, 3 menus. Reproduces 6 catalogue variant(s): navigation38, navigation39, navigation40, navigation41, navigation42, navigation43. */
export const justifiedLogoTriple: NavxPreset = {
  id: 'justified-logo-triple',
  name: 'Justified, a logo, 3 menus',
  slots: {
    menus: [{}, {}, {}],
    sections: [],
    logo: true,
    panelHeader: {
      hiddenInBar: true,
    },
    panelLogo: true,
  },
  align: 'between',
};

/** Every preset, for galleries and the Stage 5 gates. */
export const catalogue: readonly NavxPreset[] = [
  justifiedLogoSocialDualSpacedClick,
  justifiedLogoSocialDualSpaced,
  justifiedStickyLogoSocialDualSpaced,
  centeredBrand,
  plainLogo,
  justifiedLogo,
  plainLogoSectionEndButton,
  plainLogoButton,
  plainBrandSectionEndSearch,
  plainBrandSearch,
  justifiedLogoButton,
  justifiedBrandSearch,
  plainLogoSectionEndSearchButton,
  plainLogoSocialDualMenuEndSpaced,
  plainLogoDualMenuEnd,
  plainLogoDual,
  justifiedLogoDual,
  plainLogoSearch,
  justifiedLogoSearch,
  justifiedBrandSearchText,
  plainBrandDualMenuStart,
  justifiedBrandDual,
  plainLogoDualLeadMenuEnd,
  plainBrandDualMenuEnd,
  plainLogoTopBrand,
  plainLogoTop,
  centeredLogo,
  justifiedLogoTriple,
];

/**
 * Which preset reproduces which legacy fixture.
 *
 * 56 fixtures, 28 presets — the difference is variants whose chrome was
 * identical and whose content was not. The Stage 5 gates walk this map.
 */
export const byFixture: Readonly<Record<string, NavxPreset>> = {
  'ex-click': justifiedLogoSocialDualSpacedClick,
  'ex-horizontal': justifiedLogoSocialDualSpaced,
  'ex-hover': justifiedLogoSocialDualSpaced,
  'ex-lists': justifiedLogoSocialDualSpaced,
  'ex-megamenu': justifiedLogoSocialDualSpaced,
  'ex-multidropdown': justifiedLogoSocialDualSpaced,
  'ex-overlay': justifiedLogoSocialDualSpaced,
  'ex-scrollspy': justifiedStickyLogoSocialDualSpaced,
  'ex-skins': justifiedLogoSocialDualSpaced,
  'ex-sticky': justifiedStickyLogoSocialDualSpaced,
  navigation1: centeredBrand,
  navigation2: plainLogo,
  navigation3: justifiedLogo,
  navigation4: plainLogoSectionEndButton,
  navigation5: plainLogoButton,
  navigation6: plainBrandSectionEndSearch,
  navigation7: plainBrandSearch,
  navigation8: justifiedLogoButton,
  navigation9: justifiedBrandSearch,
  navigation10: plainLogoSectionEndSearchButton,
  navigation11: plainLogoSocialDualMenuEndSpaced,
  navigation12: justifiedLogoSocialDualSpaced,
  navigation13: plainLogoDualMenuEnd,
  navigation14: plainLogoDual,
  navigation15: justifiedLogoDual,
  navigation16: plainLogoDualMenuEnd,
  navigation17: plainLogoDual,
  navigation18: justifiedLogoDual,
  navigation19: justifiedLogo,
  navigation20: plainLogoSearch,
  navigation21: plainLogo,
  navigation22: justifiedLogo,
  navigation23: justifiedLogoDual,
  navigation24: justifiedLogoButton,
  navigation25: justifiedLogoSearch,
  navigation26: justifiedLogoSocialDualSpaced,
  navigation27: justifiedBrandSearchText,
  navigation28: plainBrandDualMenuStart,
  navigation29: justifiedBrandDual,
  navigation30: plainLogoDualMenuEnd,
  navigation31: justifiedLogoDual,
  navigation32: plainLogoDualLeadMenuEnd,
  navigation33: plainBrandDualMenuEnd,
  navigation34: plainLogoTopBrand,
  navigation35: plainLogoTop,
  navigation36: plainLogoTop,
  navigation37: centeredLogo,
  navigation38: justifiedLogoTriple,
  navigation39: justifiedLogoTriple,
  navigation40: justifiedLogoTriple,
  navigation41: justifiedLogoTriple,
  navigation42: justifiedLogoTriple,
  navigation43: justifiedLogoTriple,
  navigation44: justifiedLogo,
  navigation45: justifiedLogo,
  navigation46: justifiedLogo,
};
