/**
 * @navx/tokens build.
 *
 * Reads DTCG token files and emits CSS custom properties, a resolved JSON map,
 * a Sass partial, and typed TS constants.
 *
 * Written by hand rather than with Style Dictionary on purpose. Every output
 * this package needs is a custom format anyway — tier-2-only theme blocks, a
 * `:dir(rtl)` block, ten scoped skin overlays — so a token pipeline would be
 * configuration overhead without carrying any of the load. The source files stay
 * strict DTCG, so Style Dictionary remains a drop-in if Figma sync is ever
 * wanted.
 *
 * The one rule that makes theming work: in CSS, a reference emits
 * `var(--navx-other-token)` rather than the resolved literal. That keeps the
 * tier 3 → tier 2 → tier 1 chain live at runtime, which is why redefining ten
 * tier-2 tokens repaints the whole component.
 */

import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');
const PREFIX = '--navx';

const readJson = async (p) => JSON.parse(await readFile(p, 'utf8'));

/** DTCG tree → flat Map of dotted path → { type, value, description }. */
function flatten(tree, prefix = [], inheritedType = null, out = new Map()) {
  const type = tree.$type ?? inheritedType;
  for (const [key, node] of Object.entries(tree)) {
    if (key.startsWith('$')) continue;
    if (node && typeof node === 'object' && '$value' in node) {
      out.set([...prefix, key].join('.'), {
        type: node.$type ?? type,
        value: node.$value,
        description: node.$description,
      });
    } else if (node && typeof node === 'object') {
      flatten(node, [...prefix, key], node.$type ?? type, out);
    }
  }
  return out;
}

/** `surface.default` → `--navx-surface`; `link.decoration.background` → `--navx-link-decoration-background`. */
const cssName = (dotted) =>
  `${PREFIX}-${dotted
    .replace(/\.default$/, '')
    .split('.')
    .join('-')}`;

const REF = /\{([^}]+)\}/g;

/** For CSS: keep references live as var() so themes propagate through the tiers. */
const toCssValue = (value) =>
  typeof value === 'string'
    ? value.replace(REF, (_, ref) => `var(${cssName(ref)})`)
    : Array.isArray(value)
      ? `cubic-bezier(${value.join(', ')})`
      : String(value);

/** For JSON/TS: resolve all the way down to a literal. */
function resolve(value, tokens, seen = new Set()) {
  if (Array.isArray(value)) return `cubic-bezier(${value.join(', ')})`;
  if (typeof value !== 'string') return value;
  return value.replace(REF, (whole, ref) => {
    if (seen.has(ref)) throw new Error(`Circular token reference at {${ref}}`);
    const target = tokens.get(ref);
    if (!target) throw new Error(`Unresolved token reference {${ref}}`);
    return String(resolve(target.value, tokens, new Set([...seen, ref])));
  });
}

/** Every {ref} must point at a token that exists, in every file. */
function assertResolvable(tokens, label) {
  const problems = [];
  for (const [name, token] of tokens) {
    if (typeof token.value !== 'string') continue;
    for (const [, ref] of token.value.matchAll(REF)) {
      if (!tokens.has(ref)) problems.push(`${label}: ${name} → {${ref}} does not exist`);
    }
    try {
      resolve(token.value, tokens);
    } catch (err) {
      problems.push(`${label}: ${name} → ${err.message}`);
    }
  }
  if (problems.length) throw new Error(`Token graph is broken:\n  ${problems.join('\n  ')}`);
}

const block = (selector, entries, indent = '  ') =>
  `${indent.slice(2)}${selector} {\n${entries.map(([n, v]) => `${indent}${n}: ${v};`).join('\n')}\n${indent.slice(2)}}`;

async function main() {
  await rm(DIST, { recursive: true, force: true });
  await mkdir(path.join(DIST, 'skins'), { recursive: true });

  const primitive = flatten(await readJson(path.join(SRC, 'primitive.json')));
  const semantic = flatten(await readJson(path.join(SRC, 'semantic.json')));
  const component = flatten(await readJson(path.join(SRC, 'component.json')));

  const all = new Map([...primitive, ...semantic, ...component]);
  assertResolvable(all, 'base');

  const dark = flatten(await readJson(path.join(SRC, 'themes', 'dark.json')));
  assertResolvable(new Map([...all, ...dark]), 'theme:dark');

  // ── tokens.css ────────────────────────────────────────────────────────────
  const tier = (map) => [...map].map(([n, t]) => [cssName(n), toCssValue(t.value)]);

  const darkEntries = tier(dark);
  const css = [
    '/* @navx/tokens — generated by build.mjs. Do not edit. */',
    '',
    '/* tier 1 — primitives. Never redefined by a theme. Not the public API. */',
    block(':root', tier(primitive)),
    '',
    '/* tier 2 — semantic. The theming API: redefine these, not the tiers around them. */',
    block(':root', tier(semantic)),
    '',
    '/* tier 3 — component. Resolves through tier 2 only. */',
    block(':root', tier(component)),
    '',
    '/* Dark theme. Tier 2 only — 10 declarations for what legacy spent 52 on. */',
    `@media (prefers-color-scheme: dark) {\n${block('  :root:not([data-navx-theme="light"])', darkEntries, '    ')}\n}`,
    '',
    block(':root[data-navx-theme="dark"]', darkEntries),
    '',
    '/* Direction is a token, not a second stylesheet. */',
    block(':root:dir(rtl)', [
      // One declaration, and only the inline-axis arrow. The block-axis
      // rotations stay put: a submenu that drops downward drops downward in
      // Arabic too, and flipping those is what pointed every panel-mode
      // chevron upward.
      [`${PREFIX}-chevron-rotation-inline`, '135deg'],
    ]),
    '',
    '/* Arabic metrics. Latin fallbacks render Arabic with the wrong leading. */',
    block(':root:lang(ar)', [
      [`${PREFIX}-nav-font-family`, `var(${PREFIX}-font-family-arabic)`],
      [`${PREFIX}-font-line-height-tight`, `var(${PREFIX}-font-line-height-arabic)`],
    ]),
    '',
    '@media (prefers-reduced-motion: reduce) {',
    block(
      '  :root',
      [
        [`${PREFIX}-motion-duration-color`, '1ms'],
        [`${PREFIX}-motion-duration-panel`, '1ms'],
        [`${PREFIX}-motion-duration-submenu`, '1ms'],
      ],
      '    ',
    ),
    '}',
    '',
  ].join('\n');
  await writeFile(path.join(DIST, 'tokens.css'), css, 'utf8');

  // ── skins ─────────────────────────────────────────────────────────────────
  const skinDir = path.join(SRC, 'skins');
  const skinFiles = (await readdir(skinDir)).filter((f) => f.endsWith('.json'));
  const skins = [];

  for (const file of skinFiles) {
    const name = path.basename(file, '.json');
    const raw = await readJson(path.join(skinDir, file));
    const source = raw.$extends ? await readJson(path.resolve(skinDir, raw.$extends)) : raw;
    const map = flatten(source);
    assertResolvable(new Map([...all, ...map]), `skin:${name}`);
    skins.push({ name, count: map.size, description: raw.$description });
    await writeFile(
      path.join(DIST, 'skins', `${name}.css`),
      `/* @navx/tokens — skin: ${name}. Generated. */\n` +
        `${block(`[data-navx-skin="${name}"]`, tier(map))}\n`,
      'utf8',
    );
  }

  // ── resolved JSON + TS ────────────────────────────────────────────────────
  const resolved = Object.fromEntries([...all].map(([n, t]) => [n, resolve(t.value, all)]));
  await writeFile(path.join(DIST, 'tokens.json'), JSON.stringify(resolved, null, 2), 'utf8');

  await writeFile(
    path.join(DIST, '_tokens.scss'),
    `// @navx/tokens — generated. Sass consumers get the resolved literals.\n${[...all]
      .map(([n, t]) => `$navx-${n.replace(/\./g, '-')}: ${resolve(t.value, all)};`)
      .join('\n')}\n`,
    'utf8',
  );

  await writeFile(
    path.join(SRC, 'generated.ts'),
    `// Generated by build.mjs. Do not edit.\nexport const tokens = ${JSON.stringify(resolved, null, 2)} as const;\nexport const cssVars = ${JSON.stringify(
      Object.fromEntries([...all].map(([n]) => [n, cssName(n)])),
      null,
      2,
    )} as const;\nexport const skins = ${JSON.stringify(
      skins.map((s) => s.name),
      null,
      2,
    )} as const;\n`,
    'utf8',
  );

  const cssBytes = Buffer.byteLength(css);
  console.log(
    `tokens: ${primitive.size} primitive · ${semantic.size} semantic · ${component.size} component = ${all.size} total`,
  );
  console.log(`themes: 1 (dark, ${dark.size} tier-2 overrides)`);
  console.log(`skins : ${skins.length} — ${skins.map((s) => `${s.name}(${s.count})`).join(', ')}`);
  console.log(`css   : ${(cssBytes / 1024).toFixed(1)} kB raw`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
